### ISSUE TITLE
Overall Todo List

### ISSUE THREAD

**Issue by danielhickman** [danielhickman/materialcolorize#4]
- [x] Color Picker
- [ ] Finish Color Palette Creator
- [x] Convert to Material Design Colors
- [ ] Finish Color Switcher
- [ ] Finish Color Reference
- [ ] Material Design Community
- [x] Chrome App

**Comment by danielhickman** [comment]
Color Picker is at a mediocre point. I checked it off, but feel free to add, change or suggest.

**Comment by crutchcorn** [comment]
Will do.

**Comment by danielhickman** [comment]
Color Palette Creator: See http://www.google.com/design/spec/style/color.html#color-color-palette > UI Application and link to http://developer.android.com/training/material/theme.html#ColorPalette

**Comment by crutchcorn** [comment]
Do you want me to make the community page?

**Comment by danielhickman** [comment]
I think it should be a website! materialdesigncommunity.com

**Comment by danielhickman** [comment]
Color picker reached version 2.0 and convert colors at 1.0

**Comment by crutchcorn** [comment]
- [ ] Add color picker from image in convert colors (myself assigned)

**Comment by danielhickman** [comment]
More Convert Colors:
- [ ] Batch (comma separated)
- [ ] From SVG fill tag (have to be done through php exec to a ruby program)
- [ ] Span to Block on Mobile (styling to fix the width problem on mobile)

**Comment by danielhickman** [comment]
Moved to Roadmap in the Readme.md
