### ISSUE TITLE
Color Picker Todo

### ISSUE THREAD

**Issue by danielhickman** [danielhickman/materialcolorize#6]
- [ ] Add ZeroClipBoard and noFlashError with and alert
- [x] Add all colors with their values
- [x] Add Jumping by the dropdown
- [x] Add Format Changing by a dropdown
- [x] Add Color Headers
- [ ] Replace Jumping with Filtering with a  checkbox

**Comment by danielhickman** [comment]
Moved to #12 and #13
